language: node_js
sudo: false
node_js:
  - "4.2.1"
services:
  - mongodb
install:
  - npm install codecov.io --save
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec && cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js